### PR TITLE
Darwin build

### LINKED ISSUE #9: Problems with Mac version
Hi! I downloaded the [latest release](https://github.com/amitmerchant1990/electron-markdownify/releases/tag/v1.1.6) for Darwin and ran into the following issues when I opened it:
- [ ] No icon
  
  screen shot 2016-06-02 at 4 05 59 pm
- [ ] Error with the title "Markdownify cannot be opened because of a problem."
  
  "Problem Details and System Configuration" has the following output:
  
  ```
  Process:               Markdownify [13121]
  Path:                  /Users/USER/Downloads/*/Markdownify.app/Contents/MacOS/Markdownify
  Identifier:            com.electron.markdownify
  Version:               ???
  Code Type:             X86-64 (Native)
  Parent Process:        ??? [1]
  Responsible:           Markdownify [13121]
  User ID:               501
  
  Date/Time:             2016-06-02 16:08:00.935 -0700
  OS Version:            Mac OS X 10.11.4 (15E65)
  Report Version:        11
  Anonymous UUID:        D7A93E36-3690-4359-83C0-DF9DDA15586E
  
  Sleep/Wake UUID:       DF3ABACF-7AAC-4155-BE89-081781A62803
  
  Time Awake Since Boot: 37000 seconds
  Time Since Wake:       30000 seconds
  
  System Integrity Protection: enabled
  
  Crashed Thread:        0
  
  Exception Type:        EXC_BREAKPOINT (SIGTRAP)
  Exception Codes:       0x0000000000000002, 0x0000000000000000
  Exception Note:        EXC_CORPSE_NOTIFY
  
  Application Specific Information:
  dyld: launch, loading dependent libraries
  
  Dyld Error Message:
  Library not loaded: @rpath/libnode.dylib
  Referenced from: /Users/adamdrago/Downloads/Markdownify-darwin-x64/Markdownify.app/Contents/Frameworks/Electron Framework.framework/Electron Framework
  Reason: image not found
  
  Binary Images:
  0x7fff663f4000 -     0x7fff6642b0d7  dyld (360.21) <D9B236BC-4AC1-325F-B3EF-3F06DBDA7119> /usr/lib/dyld
  0x7fff877d3000 -     0x7fff877d4ffb  libSystem.B.dylib (1226.10.1) <CD307E99-FC5C-3575-BCCE-0C861AA63124> /usr/lib/libSystem.B.dylib
  0x7fff91d21000 -     0x7fff91eefff3  com.apple.QuartzCore (1.11 - 410.14) <0283748A-8318-36AC-8B30-8A951FEB305A> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
  0x7fff96688000 -     0x7fff96688fff  com.apple.Carbon (154 - 157) <8F6ED602-5943-3E29-A793-BC331E2C183D> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
  0x7fff97626000 -     0x7fff97679ff7  libc++.1.dylib (120.1) <8FC3D139-8055-3498-9AC5-6467CB7F4D14> /usr/lib/libc++.1.dylib
  
  Model: MacBookPro11,5, BootROM MBP114.0172.B09, 4 processors, Intel Core i7, 2.8 GHz, 16 GB, SMC 2.30f2
  Graphics: AMD Radeon R9 M370X, AMD Radeon R9 M370X, PCIe, 2048 MB
  Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
  Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533642465238412D50422020
  Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533642465238412D50422020
  AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x152), Broadcom BCM43xx 1.0 (7.21.95.175.1a6)
  Bluetooth: Version 4.4.4f4 17685, 3 services, 27 devices, 1 incoming serial ports
  Network Service: Display Ethernet, Ethernet, en4
  Network Service: Wi-Fi, AirPort, en0
  PCI Card: Apple 57761-B0, Ethernet Controller, Thunderbolt@192,0,0
  PCI Card: pci11c1,5901, IEEE 1394 Open HCI, Thunderbolt@191,0,0
  PCI Card: pci12d8,400e, USB Open Host Controller, Thunderbolt@197,0,0
  PCI Card: pci12d8,400e, USB Open Host Controller, Thunderbolt@197,0,1
  PCI Card: pci12d8,400f, USB Enhanced Host Controller, Thunderbolt@197,0,2
  PCI Card: Apple 57761-B0, Ethernet Controller, Thunderbolt@202,0,0
  PCI Card: pci11c1,5901, IEEE 1394 Open HCI, Thunderbolt@201,0,0
  PCI Card: pci12d8,400e, USB Open Host Controller, Thunderbolt@207,0,0
  PCI Card: pci12d8,400e, USB Open Host Controller, Thunderbolt@207,0,1
  PCI Card: pci12d8,400f, USB Enhanced Host Controller, Thunderbolt@207,0,2
  Serial ATA Device: APPLE SSD SM1024G, 1 TB
  USB Device: USB 3.0 Bus
  USB Device: Apple Internal Keyboard / Trackpad
  USB Device: Bluetooth USB Host Controller
  USB Device: USB 2.0 Bus
  USB Device: Hub
  USB Device: AppleTV
  USB Device: FaceTime HD Camera (Display)
  USB Device: Apple Thunderbolt Display
  USB Device: iPhone
  USB Device: Display Audio
  USB Device: USB 2.0 Bus
  USB Device: Hub
  USB Device: FaceTime HD Camera (Display)
  USB Device: Apple Thunderbolt Display
  USB Device: iPhone
  USB Device: Display Audio
  Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1
  Thunderbolt Device: Thunderbolt Display, Apple Inc., 1, 26.2
  ```

Let me know if you want any help with this. :)

### PR DESCRIPTION
**Pull request by atdrago**
screen shot 2016-06-04 at 1 01 37 am

This PR adds:
- Gulp task for osx
- Gulp stub tasks for windows and linux

And an npm script:
- `npm run build` - delete the previously created `dist` folder, and create it again with built apps inside

Make sure you run `npm install` after merging. :)

Resolves #9

### CODE REVIEW

File: gulpfile.js [hunk 1]
```diff
@@ -0,0 +1,45 @@
+'use strict';
+
+const fs = require('fs');
+const gulp = require('gulp');
+const packager = require('electron-packager');
+
+const config = JSON.parse(fs.readFileSync('package.json'));
+const appVersion = config.version;
+const electronVersion = config.devDependencies['electron-prebuilt'].match(/[\d.]+/)[0];
```
Comment (atdrago) [inline gulpfile.js:9]: Just a note that this will not always be accurate if your package.json doesn't specify the latest version of electron-prebuilt that satisifies the semver string. E.g., if the package.json says `"electron-prebuilt": "^0.36.0"`, the Electron version you're using is actually `0.36.12`, so your package.json should be updated to `"electron-prebuilt": "^0.36.12"` for your build to grab the correct Electron version.

Hope that makes sense. 🙃
